### ISSUE TITLE
onEdit hook.

### ISSUE THREAD

**Issue by allanhortle** [dxinteractive/react-entity-editor#2]
Sometimes an edit call can be super destructive. E.g. click a trash button to delete a section of a complex form. It's still an edit action but it would be nice to have a confirm box pop up.

**Comment by dxinteractive** [comment]
This has been included in [v0.1.2](https://github.com/dxinteractive/react-entity-editor/releases/tag/v0.1.2.) An `onCustomConfirm` prop is passed down from `EntityEditor`, which accepts a function that you can define on your form. The function should return an object with all the details for the confirmation pop up, such as `type`, `title`, `message`, `yes` and `no`. The details of the data shape for modals hasn't been fully documented yet, but it follows the same shape as all other prompts defined in `src/TextDefaults.js`*.

`onCustomConfirm` returns a `Promise` which will be resolved if the user confirms the action, or will be rejected if the user cancels the action. You can use it like this:

```
this.props.onCustomConfirm(() => ({
    type: "confirm",
    title: "Warning",
    message: `Are you sure you want to change the user type to "${userType}"?`,
    yes: "Yes",
    no: "Cancel"
})).then(() => {
    // stuff to do if the user confirms the action
});   
```

I've also added an example usage in `BasicEntityEditorForm`.

*One difference: you don't have to pass `onYes` and `onNo` explicitly through `onCustomConfirm`, where as this is currently required on other prompts. It's likely I'll restructure this a bit so that not even the default prompts don't need to to pass `onYes` and `onNo` explicitly.
